### ISSUE TITLE
Package does not compile

### ISSUE THREAD

**Issue by essentialols** [omegahat/RTidyHTML#2]
The package does not compile on RStudio 2022.02.2 Build 485 with R version 4.2.0 with the following error message:

gcc -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Ilibtidy/include  -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c Rtidy.c -o Rtidy.o
Rtidy.c:33:3: error: use of undeclared identifier 'PROBLEM'
  PROBLEM msg
  ^
Rtidy.c:81:7: error: use of undeclared identifier 'PROBLEM'
      PROBLEM "problem parsing the HTML document"
      ^
Rtidy.c:86:7: error: use of undeclared identifier 'PROBLEM'
      PROBLEM "problem tidying the HTML document"
      ^
Rtidy.c:91:7: error: use of undeclared identifier 'PROBLEM'
      PROBLEM "problem running the diagnostics on the HTML document"
      ^
4 errors generated.
make: *** [Rtidy.o] Error 1
ERROR: compilation failed for package ‘RTidyHTML’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RTidyHTML’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/14/wjhgvnh97gl7b545trmwmsl80000gn/T//RtmpCNE75X/file6e7b44931029/RTidyHTML_0.2-1.tar.gz’ had non-zero exit status
